export const bible = [
  {
    book: "Genesis",
    chapters: [
      {
        chapter: 1,
        verses: [
            "In the beginning God created the heavens and the earth.",
            "Now the earth was formless and empty, darkness was over the surface of the deep, and the Spirit of God was hovering over the waters.",
            "And God said, “Let there be light,” and there was light.",
            "God saw that the light was good, and he separated the light from the darkness.",
            "God called the light “day,” and the darkness he called “night.” And there was evening, and there was morning—the first day.",
            "And God said, “Let there be a vault between the waters to separate water from water.”",
            "So God made the vault and separated the water under the vault from the water above it. And it was so.",
            "God called the vault “sky.” And there was evening, and there was morning—the second day.",
            "And God said, “Let the water under the sky be gathered to one place, and let dry ground appear.” And it was so.",
            "God called the dry ground “land,” and the gathered waters he called “seas.” And God saw that it was good.",
            "Then God said, “Let the land produce vegetation: seed-bearing plants and trees on the land that bear fruit with seed in it, according to their various kinds.” And it was so.",
            "The land produced vegetation: plants bearing seed according to their kinds and trees bearing fruit with seed in it according to their kinds. And God saw that it was good.",
            "And there was evening, and there was morning—the third day.",
            "And God said, “Let there be lights in the vault of the sky to separate the day from the night, and let them serve as signs to mark sacred times, and days and years,",
            "and let them be lights in the vault of the sky to give light on the earth.” And it was so.",
            "God made two great lights—the greater light to govern the day and the lesser light to govern the night. He also made the stars.",
            "God set them in the vault of the sky to give light on the earth,",
            "to govern the day and the night, and to separate light from darkness. And God saw that it was good.",
            "And there was evening, and there was morning—the fourth day.",
            "And God said, “Let the water teem with living creatures, and let birds fly above the earth across the vault of the sky.”",
            "So God created the great creatures of the sea and every living thing with which the water teems and that moves about in it, according to their kinds, and every winged bird according to its kind. And God saw that it was good.",
            "God blessed them and said, “Be fruitful and increase in number and fill the water in the seas, and let the birds increase on the earth.”",
            "And there was evening, and there was morning—the fifth day.",
            "And God said, “Let the land produce living creatures according to their kinds: the livestock, the creatures that move along the ground, and the wild animals, each according to its kind.” And it was so.",
            "God made the wild animals according to their kinds, the livestock according to their kinds, and all the creatures that move along the ground according to their kinds. And God saw that it was good.",
            "Then God said, “Let us make mankind in our image, in our likeness, so that they may rule over the fish in the sea and the birds in the sky, over the livestock and all the wild animals, and over all the creatures that move along the ground.”",
            "So God created mankind in his own image, in the image of God he created them; male and female he created them.",
            "God blessed them and said to them, “Be fruitful and increase in number; fill the earth and subdue it. Rule over the fish in the sea and the birds in the sky and over every living creature that moves on the ground.”",
            "Then God said, “I give you every seed-bearing plant on the face of the whole earth and every tree that has fruit with seed in it. They will be yours for food.",
            "And to all the beasts of the earth and all the birds in the sky and all the creatures that move along the ground—everything that has the breath of life in it—I give every green plant for food.” And it was so.",
            "God saw all that he had made, and it was very good. And there was evening, and there was morning—the sixth day."
        ],
      },
      {
        chapter: 2,
        verses: [
          "Thus the heavens and the earth were completed in all their vast array.",
          "By the seventh day God had finished the work he had been doing; so on the seventh day he rested from all his work.",
          "Then God blessed the seventh day and made it holy, because on it he rested from all the work of creating that he had done.",
          "This is the account of the heavens and the earth when they were created, when the LORD God made the earth and the heavens.",
          "Now no shrub had yet appeared on the earth and no plant had yet sprung up, for the LORD God had not sent rain on the earth and there was no one to work the ground,",
          "but streams came up from the earth and watered the whole surface of the ground.",
          "Then the LORD God formed a man from the dust of the ground and breathed into his nostrils the breath of life, and the man became a living being.",
          "Now the LORD God had planted a garden in the east, in Eden; and there he put the man he had formed.",
          "The LORD God made all kinds of trees grow out of the ground—trees that were pleasing to the eye and good for food. In the middle of the garden were the tree of life and the tree of the knowledge of good and evil.",
          "A river watering the garden flowed from Eden; from there it was separated into four headwaters.",
          "The name of the first is the Pishon; it winds through the entire land of Havilah, where there is gold.",
          "(The gold of that land is good; aromatic resin and onyx are also there.)",
          "The name of the second river is the Gihon; it winds through the entire land of Cush.",
          "The name of the third river is the Tigris; it runs along the east side of Ashur. And the fourth river is the Euphrates.",
          "The LORD God took the man and put him in the Garden of Eden to work it and take care of it.",
          "And the LORD God commanded the man, “You are free to eat from any tree in the garden;",
          "but you must not eat from the tree of the knowledge of good and evil, for when you eat from it you will certainly die.”",
          "The LORD God said, “It is not good for the man to be alone. I will make a helper suitable for him.”",
          "Now the LORD God had formed out of the ground all the wild animals and all the birds in the sky. He brought them to the man to see what he would name them; and whatever the man called each living creature, that was its name.",
          "So the man gave names to all the livestock, the birds in the sky and all the wild animals. But for Adam no suitable helper was found.",
          "So the LORD God caused the man to fall into a deep sleep; and while he was sleeping, he took one of the man’s ribs and then closed up the place with flesh.",
          "Then the LORD God made a woman from the rib he had taken out of the man, and he brought her to the man.",
          "The man said, “This is now bone of my bones and flesh of my flesh; she shall be called ‘woman,’ for she was taken out of man.”",
          "That is why a man leaves his father and mother and is united to his wife, and they become one flesh.",
          "Adam and his wife were both naked, and they felt no shame."
        ],
      },
    ],
  },
  {     
    book: "창세기",
    chapters: [
      {
        chapter: 1,
        verses: [
            "In the beginning...",
            "태초에 하나님이 천지를 창조하시니라", 
            "땅이 혼돈하고 공허하며 흑암이 깊음 위에 있고 하나님의 신은 수면에 운행하시니라",
            "하나님이 가라사대 빛이 있으라 하시매 빛이 있었고",
            "그 빛이 하나님의 보시기에 좋았더라 하나님이 빛과 어두움을 나누사",
            "빛을 낮이라 칭하시고 어두움을 밤이라 칭하시니라 저녁이 되며 아침이 되니 이는 첫째 날이니라",
            "하나님이 가라사대 물 가운데 궁창이 있어 물과 물로 나뉘게 하리라 하시고",
            "하나님이 궁창을 만드사 궁창 아래의 물과 궁창 위의 물로 나뉘게 하시매 그대로 되니라",
            "하나님이 궁창을 하늘이라 칭하시니라 저녁이 되며 아침이 되니 이는 둘째 날이니라",
            "하나님이 가라사대 천하의 물이 한 곳으로 모이고 뭍이 드러나라 하시매 그대로 되니라",
            "하나님이 뭍을 땅이라 칭하시고 모인 물을 바다라 칭하시니라 하나님의 보시기에 좋았더라",
            "하나님이 가라사대 땅은 풀과 씨 맺는 채소와 각기 종류대로 씨 가진 열매 맺는 과목을 내라 하시매 그대로 되어",
            "땅이 풀과 각기 종류대로 씨 맺는 채소와 각기 종류대로 씨 가진 열매 맺는 나무를 내니 하나님의 보시기에 좋았더라",
            "저녁이 되며 아침이 되니 이는 셋째 날이니라",
            "하나님이 가라사대 하늘의 궁창에 광명이 있어 주야를 나뉘게 하라 또 그 광명으로 하여 징조와 사시와 일자와 연한이 이루라",
            "또 그 광명이 하늘의 궁창에 있어 땅에 비취라 하시고 (그대로 되니라)",
            "하나님이 두 큰 광명을 만드사 큰 광명으로 낮을 주관하게 하시고 작은 광명으로 밤을 주관하게 하시며 또 별들을 만드시고",
            "하나님이 그것들을 하늘의 궁창에 두어 땅에 비취게 하시며",
            "주야를 주관하게 하시며 빛과 어두움을 나뉘게 하시니라 하나님의 보시기에 좋았더라",
            "저녁이 되며 아침이 되니 이는 넷째 날이니라",
            "하나님이 가라사대 물들은 생물로 번성케 하라 땅 위 하늘의 궁창에는 새가 날으라 하시고",
            "하나님이 큰 물고기와 물에서 번성하여 움직이는 모든 생물을 그 종류대로, 날개 있는 모든 새를 그 종류대로 창조하시니 하나님의 보시기에 좋았더라",
            "하나님이 그들에게 복을 주어 가라사대 생육하고 번성하여 여러 바다 물에 충만하라 새들도 땅에 번성하라 하시니라",
            "저녁이 되며 아침이 되니 이는 다섯째 날이니라",
            "하나님이 가라사대 땅은 생물을 그 종류대로 내되 육축과 기는 것과 땅의 짐승을 종류대로 내라 하시고 (그대로 되니라)",
            "하나님이 땅의 짐승을 그 종류대로 육축을 그 종류대로 땅에 기는 모든 것을 그 종류대로 만드시니 하나님의 보시기에 좋았더라",
            "하나님이 가라사대 우리의 형상을 따라 우리의 모양대로 우리가 사람을 만들고 그로 바다의 고기와 공중의 새와 육축과 온 땅과 땅에 기는 모든 것을 다스리게 하자 하시고",
            "하나님이 자기 형상 곧 하나님의 형상대로 사람을 창조하시되 남자와 여자를 창조하시고",
            "하나님이 그들에게 복을 주시며 그들에게 이르시되 생육하고 번성하여 땅에 충만하라, 땅을 정복하라, 바다의 고기와 공중의 새와 땅에 움직이는 모든 생물을 다스리라 하시니라",
            "하나님이 가라사대 내가 온 지면의 씨 맺는 모든 채소와 씨 가진 열매 맺는 모든 나무를 너희에게 주노니 너희 식물이 되리라",
            "또 땅의 모든 짐승과 공중의 모든 새와 생명이 있어 땅에 기는 모든 것에게는 내가 모든 푸른 풀을 식물로 주노라 하시니 그대로 되니라",
            "하나님이 그 지으신 모든 것을 보시니 보시기에 심히 좋았더라 저녁이 되며 아침이 되니 이는 여섯째 날이니라",
        ],
      },
      {
        chapter: 2,
        verses: [
          "천지와 만물이 다 이루어지니라",
          "하나님이 그가 하시던 일을 일곱째 날에 마치시니",
        ],
      },
    ],

  },
  {
    book: "요한복음",
    chapters: [
      {
        chapter: 1,
        verses: [
          "태초에 말씀이 계시니라 이 말씀이 하나님과 함께 계셨으니",
          "이 말씀은 곧 하나님이시니라",
        ],
      },
    ],
  },
];